function dJdx = calc_dJdx(x,nu,alpha,Lref)

imax = length(x);
dxi = 1;

% x_xi = dnfdxn(x,dxi,1,2);
% x_xixi = dnfdxn(x,dxi,2,2);
x_xi = dudx(x,dxi);
x_xixi = d2udx2(x,dxi);


TE = Burgers_TE(x,x_xi,x_xixi,dxi,nu,alpha,Lref);

i = 2:imax-1;
    uex=     uxn(x(i),nu,alpha,Lref,0);
    ux =     uxn(x(i),nu,alpha,Lref,1);
    uxx =    uxn(x(i),nu,alpha,Lref,2);
    uxxx =   uxn(x(i),nu,alpha,Lref,3);
    uxxxx =  uxn(x(i),nu,alpha,Lref,4);
    uxxxxx = uxn(x(i),nu,alpha,Lref,5);

    dTEi_dxvec(i) = dTE_dxi(uex,             ...
                           ux,               ...
                           uxx,              ...
                           uxxx,             ...
                           uxxxx,            ...
                           uxxxxx,           ...
                           x_xi(i),          ...
                           x_xixi(i),        ...
                           dxi,              ...
                           nu,               ...
                           alpha,            ...
                           Lref,             ...
                           0);

    uex=     uxn(x(i+1),nu,alpha,Lref,0);
    ux =     uxn(x(i+1),nu,alpha,Lref,1);
    uxx =    uxn(x(i+1),nu,alpha,Lref,2);
    uxxx =   uxn(x(i+1),nu,alpha,Lref,3);
    uxxxx =  uxn(x(i+1),nu,alpha,Lref,4);
    uxxxxx = uxn(x(i+1),nu,alpha,Lref,5);
    
    dTEip1_dxvec(i) = dTE_dxi(uex,           ...
                           ux,               ...
                           uxx,              ...
                           uxxx,             ...
                           uxxxx,            ...
                           uxxxxx,           ...
                           x_xi(i+1),        ...
                           x_xixi(i+1),      ...
                           dxi,              ...
                           nu,               ...
                           alpha,            ...
                           Lref,             ...
                           1);


    uex=     uxn(x(i-1),nu,alpha,Lref,0);
    ux =     uxn(x(i-1),nu,alpha,Lref,1);
    uxx =    uxn(x(i-1),nu,alpha,Lref,2);
    uxxx =   uxn(x(i-1),nu,alpha,Lref,3);
    uxxxx =  uxn(x(i-1),nu,alpha,Lref,4);
    uxxxxx = uxn(x(i-1),nu,alpha,Lref,5);
    
    dTEim1_dxvec(i) = dTE_dxi(uex,           ...
                           ux,               ...
                           uxx,              ...
                           uxxx,             ...
                           uxxxx,            ...
                           uxxxxx,           ...
                           x_xi(i-1),        ...
                           x_xixi(i-1),      ...
                           dxi,              ...
                           nu,               ...
                           alpha,            ...
                           Lref,             ...
                           -1);

                                           
                    



  dJdx = analytic_dJdx(x,...
                     TE,dTEi_dxvec,dTEip1_dxvec,dTEim1_dxvec,...
                     imax);




end