DEFSDIR=../

BINDIR = ../../bin/
SRCDIR = ./src
OBJDIR = ./obj
VPATH = $(SRCDIR): $(OBJDIR)
LIB= 

#define source files and output files ---------------
EXE =  burgers2d_n9_re8.exe
OBJ =  2DCurvilinear-Burger.o

#include standard definitions for compilation -------

include $(DEFSDIR)/std_defs.mk

#define dependencies ---------------------------------

burgerssteadysolver.o :

$(EXE) : $(OBJ)
