DEFSDIR=../

BINDIR = ../../bin/
SRCDIR = ./src
OBJDIR = ./obj
VPATH = $(SRCDIR): $(OBJDIR)

#define source files and output files ---------------
EXE =  burgers_n17_re32.exe
OBJ =  burgerssteadysolver.o

#include standard definitions for compilation -------

include $(DEFSDIR)/std_defs.mk

#define dependencies ---------------------------------

burgerssteadysolver.o :

$(EXE) : $(OBJ)
